version: '3.6'
services:
  mongo:
    container_name: dunia-mongo
    image: mongo:4.2
    command: --replSet dunia-rs --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - dunia
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb-cfg
        target: /data/configdb
  mongo-replicator:
    container_name: dunia-mongo-replicator
    build: ./mongo-replicator
    environment:
      - HOST=mongo
      - PORT=27017
      - USERNAME=root
      - PASSWORD=root
      - REPLICA_SET_NAME=dunia-rs
    networks:
      - dunia
    depends_on:
      - mongo
  api:
    container_name: dunia-api
    build:
      context: ./
      dockerfile: Dockerfile.dev
    networks:
      - dunia
    environment:
      APP_ENV: development
    volumes:
      - ./src:/app/src
    ports:
      - 8081:8081
      - 8082:8082
    env_file:
      - ./development.env
    depends_on:
      #   - redis
      - mongo-replicator
networks:
  dunia:
    name: dunia-network

volumes:
  mongodb:
  mongodb-cfg:
