FROM node:12-alpine

RUN apk update

EXPOSE 8080

EXPOSE 8080
COPY ["./package.json", "./package-lock.json", "tsconfig.build.json", "tsconfig.json", "/app/"]
WORKDIR /app

RUN npm ci --quiet

VOLUME "/app/src"

CMD npm run start:dev
