FROM node:12-alpine

RUN apk update

EXPOSE 3001

COPY ["./package.json", "./package-lock.json", "tsconfig.build.json", "tsconfig.json", ".env.development", ".env.production", "/app/"]

WORKDIR /app

RUN npm ci --quiet

VOLUME "/app/src"

CMD npm run start:dev
